bbaga/github-scheduled-reminder-app

- README.md
- docker-compose.yaml
- pom.xml
- src/main/java/com/bbaga/githubscheduledreminderapp/Config.java
- src/main/java/com/bbaga/githubscheduledreminderapp/GitHubAppInstallationService.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/ConfigGraphNode.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/ConfigGraphUpdater.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/InRepoConfigParser.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/persistence/ConfigPersistenceFactory.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/persistence/ConfigPersistenceInterface.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/persistence/ConfigPersistenceLocalFile.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/persistence/ConfigPersistenceLocalFileSettings.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/persistence/ConfigPersistenceSettingsInterface.java
- src/main/java/com/bbaga/githubscheduledreminderapp/controllers/GitHubEventHandler.java
- src/main/java/com/bbaga/githubscheduledreminderapp/controllers/State.java
- src/main/java/com/bbaga/githubscheduledreminderapp/jobs/GitHubInstallationRepositoryScan.java
- src/main/java/com/bbaga/githubscheduledreminderapp/jobs/ScheduledStateDump.java
- src/main/resources/application.properties
- src/test/java/com/bbaga/githubscheduledreminderapp/repositories/GitHubInstallationRepositoryTest.java
Code cleanup and adding state dumping/restoring support
> Code cleanup and adding state dumping/restoring support

- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/GitHub/AppInstallationContainer.java
- src/main/java/com/bbaga/githubscheduledreminderapp/repositories/GitHubInstallationRepository.java
- src/test/java/com/bbaga/githubscheduledreminderapp/repositories/GitHubInstallationRepositoryTest.java
Re-enable installation repository tests
> Re-enable installation repository tests

- src/main/java/com/bbaga/githubscheduledreminderapp/Config.java
- src/main/java/com/bbaga/githubscheduledreminderapp/GitHubAppInstallationService.java
- src/main/java/com/bbaga/githubscheduledreminderapp/controllers/State.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/GitHub/GitHubBuilderFactory.java
- src/main/java/com/bbaga/githubscheduledreminderapp/jobs/GitHubInstallationRepositoryScan.java
> Fix GitHub API url usage

- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/GitHub/GitHubBuilderFactory.java
Small cosmetic fix in GitHubBuilderFactory
> Small cosmetic fix in GitHubBuilderFactory

- src/main/java/com/bbaga/githubscheduledreminderapp/GitHubAppInstallationService.java
> Add token expiration buffer

- src/main/java/com/bbaga/githubscheduledreminderapp/notifications/slack/ChannelNotificationDataProvider.java
Filter out Draft PRs as there is no use-case for their listing at this time. Issue regarding custom filter options #17.
> Query Issues and PRs separatly, only list PRs if they aren't draft

- src/main/java/com/bbaga/githubscheduledreminderapp/Config.java
- src/main/java/com/bbaga/githubscheduledreminderapp/GitHubAppInstallationService.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/ConfigGraphUpdater.java
- src/main/java/com/bbaga/githubscheduledreminderapp/configuration/RepositoryInstallationEventListener.java
- src/main/java/com/bbaga/githubscheduledreminderapp/controllers/GitHubEventHandler.java
- src/main/java/com/bbaga/githubscheduledreminderapp/controllers/State.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/AppInstallationContainer.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/GitHubBuilderFactory.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/webhook/EventPublisher.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/webhook/events/RepositoryInstallationEvent.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/webhook/events/WebhookEvent.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/webhook/events/WebhookEventInterface.java
- src/main/java/com/bbaga/githubscheduledreminderapp/jobs/GitHubInstallationRepositoryScan.java
- src/main/java/com/bbaga/githubscheduledreminderapp/jobs/GitHubInstallationScan.java
- src/main/java/com/bbaga/githubscheduledreminderapp/jobs/scheduling/InstallationScanJobScheduler.java
- src/main/java/com/bbaga/githubscheduledreminderapp/repositories/GitHubInstallationRepository.java
- src/main/resources/application-test.properties
- src/test/java/com/bbaga/githubscheduledreminderapp/configuration/RepositoryInstallationEventListenerTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/controllers/GitHubEventHandlerTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/repositories/GitHubInstallationRepositoryTest.java
> Register new repository installation through webhooks

- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/webhook/EventPublisher.java
- src/test/java/com/bbaga/githubscheduledreminderapp/application/controllers/GitHubEventHandlerTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/webhook/EventPublisherTest.java
> Ignore webhook events we aren't interested in

- README.md
- docs/sources.md
Add documentation for sources. Give examples and short descriptions.
> Add documentation for sources

- docs/sources.md
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/SearchPRsByReviewersSource.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/FilterChain.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/RepositoryIssuesSource.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/RepositoryPRsSource.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/SearchByReviewersPRsSource.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/SearchIssuesSource.java
- src/test/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/InRepoConfigParserTest.java
Add filter support for all sources
> Add filter support for all sources

- src/main/java/com/bbaga/githubscheduledreminderapp/application/controllers/State.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/ConfigGraphUpdater.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/configuration/ConfigGraphUpdaterTest.java
Add config buffer for extension if parent config has not been discovered yet.
Closes #25
> Add config buffer for extension if parent config has not been discovered yet

- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/RepositoryInstallationEventListener.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/SearchByReviewersPRsSource.java
> Fix search-prs-by-reviewers source: search for only open PRs

- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotification.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotificationTest.java
> Limit the number issues and PRs in a notification to max 20 entires of each type

- pom.xml
> Bump log4j

- src/main/java/com/bbaga/githubscheduledreminderapp/application/controllers/State.java
> Fix stack exposure

- README.md
- docs/persistent-state-storage.md
- src/main/java/com/bbaga/githubscheduledreminderapp/application/Config.java
- src/main/java/com/bbaga/githubscheduledreminderapp/application/PersistentStorageConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/application/jobs/ScheduledStateDump.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/persitance/ConfigPersistenceFactory.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/persitance/ConfigPersistenceGCSBucket.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/persitance/ConfigPersistenceGCSBucketSettings.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/persitance/ConfigPersistenceInterface.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/persitance/ConfigPersistenceLocalFile.java
```
STATE_STORAGE_TYPE=GCS_BUCKET
STATE_STORAGE_GCS_BUCKET_NAME=my-gcs-bucket
STATE_STORAGE_GCS_BUCKET_SECRET_FILE=/secure/location/credentials.json
STATE_STORAGE_GCS_BUCKET_FILEPATH=application.state.json
```
Closes #46
> Implement configuration storage to GCS

- src/main/java/com/bbaga/githubscheduledreminderapp/application/Config.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotification.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/StatisticsConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/StatisticsEvent.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/StatisticsEventListener.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotificationTest.java
Add notification stats to make the number fo messages and items posted on slack channels.
> Add notification stats

- README.md
- docs/sources.md
- docs/template-config.md
- src/main/java/com/bbaga/githubscheduledreminderapp/application/jobs/ScheduledNotification.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/configuration/RepositoryInstallationEventListenerTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/InRepoConfigParserBackwardsCompatibilityTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/infrastructure/configuration/InRepoSlackScheduledConfigParserTest.java
> Add documentation for template configuration options

- pom.xml
> Version bump to 0.8.0

- src/main/java/com/bbaga/githubscheduledreminderapp/application/jobs/ScheduledNotification.java
Keep backwards compatibility for scheduled Slack notifications
> Keep backwards compatibility for scheduled Slack notifications

- docs/sources.md
- pom.xml
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/SourceConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/filters/AuthorFilterConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/filters/Filters.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/RepositoryIssuesSource.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/RepositoryPRsSource.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/AuthorFilter.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/FilterProvider.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/LabelFilter.java
Introducing a new filter called `author-filter`.
```yaml
filters:
- type: athor-filter
include:
- usernameA
- usernameB
```
> Add author-filter

- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelMessageBuilder.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelMessageBuilderInterface.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotification.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/AggregatedStatisticsStorage.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/PassThroughUrlBuilder.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/StatisticsEvent.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/StatisticsEventListener.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/TrackingUrlBuilder.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/statistics/UrlBuilderInterface.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotificationTest.java
Counter for displayed issues/prs in reports
Tracking click on channel basis
> Fix counter for posted issues + add channel click tracking

- docs/template-config.md
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelMessageBuilder.java
- src/main/java/com/bbaga/githubscheduledreminderapp/infrastructure/github/GitHubPullRequest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotificationTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/DraftFilterTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/PathFilterTest.java
Added in requested reviewers for GitHub PR types
> Adding in Requested Reviewer replacement option

- src/main/java/com/bbaga/githubscheduledreminderapp/application/config/SchedulerConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/application/jobs/SlackChannelMessageDelete.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/ChannelNotification.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/SearchAndDeleteEvent.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/SearchAndDeleteEventListener.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/SearchMessageQueueItem.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/SearchRequest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/notifications/slack/SearchMessageQueueItemTest.java
> Fix previous message deletion

- docs/sources.md
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/filters/AuthorFilterConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/filters/DraftFilterConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/filters/LabelFilterConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/configuration/sources/filters/PathFilterConfig.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/AuthorFilter.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/DraftFilter.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/ExpireableFilter.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/LabelFilter.java
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/filters/PathFilter.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/AuthorFilterTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/LabelFilterTest.java
- src/test/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/PathFilterTest.java
Added inputs so all Filters had Include, Exclude, and expiration options
Changed filters to never expire so that these can be set by users instead of randomly expire in 90 days.
Added unit tests so all filters have a basic set of tests.
> Adding in include, exclude, and expiration to all filters

- .gitignore
- src/main/java/com/bbaga/githubscheduledreminderapp/domain/sources/github/SearchByReviewersPRsSource.java
> Reset the search builder object in SearchByReviewersPRsSource for every username

- CONTRIBUTING.md
- README.md
- docs/README.md
Update documentation, contribution and readme:
- added supported by section
- need of signed commits in PRs
- bit of description of the tool in the documentation
> Documentation update
